apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::469684750733:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1NOWB5PVZJCUR
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::469684750733:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-02T06:17:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1585"
  uid: 537c36cf-f84a-4896-87e9-8665f3d5ed33
